### ISSUE TITLE
Type Generation : returned payload type on upsert not using include

### ISSUE THREAD

**Issue by squirly** [prisma/prisma-client-js#660]
Breaking commit: https://github.com/prisma/prisma/commit/4cee9296e77e63aa856f60b9a33555ab01d9b039#diff-55d3b6703244dc96a4a668b570e5c70d

^^ Issue is caused by the above commit, related to prisma/prisma#615. There is not explanation given as to why this change was made. @timsuchanek could you clarify this change? 

## Bug description

The `include` option only expands the result type when the query options passed to the Prisma Client extend the `findMany` options.
 
The following line decides when `includes` will expand the return type:
https://github.com/prisma/prisma/blob/c86af74877d9f39936b18276b3c1db8d5ff7b310/src/packages/client/src/generation/TSClient.ts#L553

## How to reproduce

Add includes to an `upsert`, or `findOne` that uses a `where` with a composite unique lookup, that is not available in `{...}WhereInput`.

Using the blog fixture example:

```
model Like {
  id  String  @default(cuid()) @id

  userId  String
  user    User    @relation(fields: [userId], references: [id])

  postId  String
  post    Post    @relation(fields: [postId], references: [id])

  @@unique([userId, postId])
}
```

```ts
  const like = await prisma.like.upsert({
    where: {
      userId_postId: {
        userId: userId,
        postId: post.id,
      }
    },
    create: {
      post: {connect: {id: post.id}},
      user: {connect: {id: userId}},
    },
    update: {},
    include: {post: true},
  });

  const p = like.post;
                 |--|
                 ^ TS2339: Property 'post' does not exist on type 'Like'.
```

`typeof like` is `Like` despite the includes.

## Expected behavior

The type correctly has the fields specified in `includes`.

In the above example, `typeof like` should be `Like & {post: Post}`.

## Prisma information

Example in https://github.com/squirly/prisma/tree/bug-example/src/packages/client/fixtures/blog

## Environment & setup

- OS: Mac OS & Arch
- Database: PostgreSQL
- Prisma version:
  - Broken in: 2.0.0-beta.2
  - Works in 2.0.0-beta.1
- Node.js version: 12.16.1

**Comment by timsuchanek** [comment]
Thanks for reporting @squirly.
As mentioned in the commit (https://github.com/prisma/prisma/commit/4cee9296e77e63aa856f60b9a33555ab01d9b039#diff-0cc91727f49088eeb56266cf1b886c81R131) the fix I introduced there was about the nested `findMany` with `orderBy` case.
Your PR would have broken that case again.
Instead, I now added a type union, which is executed in the type inference by 2 separate statements. (Does it extend the first type? If not, check if it extends the second type).

This issue is fixed in the latest alpha version of `@prisma/cli`.
You can try it out with `npm i -g @prisma/cli@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!
